const STAMP_RE = /\n+---\n+\*Generated by \[RepoDoc\][^\n]*\*\n*$/;
export function generationStamp(opts: {
  repoUrl?: string | null;
  commitSha?: string | null;
}): string {
  const repo = opts.repoUrl
    ? opts.repoUrl
        .replace(/^https?:\/\/(www\.)?github\.com\//, "")
        .replace(/\.git$/, "")
        .replace(/\/+$/, "")
    : null;
  const at = opts.commitSha ? `@${opts.commitSha.slice(0, 7)}` : "";
  const date = new Date().toISOString().slice(0, 10);
  const source = repo ? ` from \`${repo}${at}\`` : "";
  return `\n\n---\n\n*Generated by [RepoDoc](https://repodoc.parbhat.dev)${source} · ${date}*\n`;
}

export function stripGenerationStamp(content: string): string {
  return content.replace(STAMP_RE, "\n");
}

export function withGenerationStamp(
  content: string,
  opts: { repoUrl?: string | null; commitSha?: string | null },
): string {
  return stripGenerationStamp(content.trimEnd()) + generationStamp(opts);
}
