import {
  generationStamp,
  stripGenerationStamp,
  withGenerationStamp,
} from "@/lib/generated-stamp";

describe("generationStamp", () => {
  it("names the repo and short commit", () => {
    const stamp = generationStamp({
      repoUrl: "https://github.com/acme/ledger.git",
      commitSha: "9f31c2eabcdef1234567890",
    });
    expect(stamp).toContain("`acme/ledger@9f31c2e`");
    expect(stamp).toContain(
      "Generated by [RepoDoc](https://repodoc.parbhat.dev)",
    );
  });

  it("omits the source clause without a repo url", () => {
    const stamp = generationStamp({});
    expect(stamp).not.toContain("from");
    expect(stamp).toContain("Generated by [RepoDoc]");
  });
});

describe("withGenerationStamp", () => {
  it("does not stack stamps across regenerations", () => {
    const opts = {
      repoUrl: "https://github.com/acme/ledger",
      commitSha: "abc1234",
    };
    const once = withGenerationStamp("# Doc\n\nBody.", opts);
    const twice = withGenerationStamp(once, opts);
    expect(twice.match(/Generated by \[RepoDoc\]/g)).toHaveLength(1);
    expect(stripGenerationStamp(twice)).not.toContain("Generated by");
    expect(stripGenerationStamp(twice)).toContain("Body.");
  });
});
